#!/usr/bin/env bash


BASH_MAJOR=${BASH_VERSION:0:1}
BASH_MINOR=${BASH_VERSION:2:1}

if [[ ${BASH_VERSINFO[0]} -gt 4 || ( ${BASH_VERSINFO[0]} -eq 4 && ${BASH_VERSINFO[1]} -ge 4 ) ]]
then
    echo "BASH VERSION >= 4.4: $BASH_VERSION"
    # file d\ne has a newline which is also the read delimiter so we get 4 files instead of three
    # *** REQUIRES BASH 4.4 ***
    find files -type f -print0 | while read -r -d'' file
    do
        echo "<$file>"
    done
else
    echo "BASH VERSION < 4.4: $BASH_VERSION"
    # Using xargs is a more portable way to handle null-delimited streams
    # if the bash version is older than 4.4.
    find files -type f -print0 | xargs -0 -I {} echo "<{}>"
fi
